Validate connection and refresh preloaded data on login
Reiryoku-Technologies/Mida pull request #109
Opened 2023-05-12 09:20 UTC by JoeGuest

When running Mida in AWS Lambda, I've found that the account and connection stays open in-between invocations.

The account is retained in the Lambda Execution Environment as it is declared in global scope (`const loggedAccounts: Map<string, CTraderAccount> = new Map();` in `CTrader.ts`), and therefore subsequent invocations can re-use the account.

There were two problems with this that caused unexpected behaviour.:
- The connection may drop between invocations
- The preloaded data would be out of date

The solution I've put together in this PR involves checking if the account is still connected followed by re-fetching the preloaded data if it is, if not it will remove the old one from the loggedAccounts and establish a new connection. My thinking regarding re-fetching is that if someone is calling `.login()` again they would want the latest data on the account at the time (e.g. my Lambda findings, they'd thought the account had disconnected and tried to connect again etc).

I'm aware my implementation isn't ideal, and I'm not sure the best way to check the connection details so I've just chosen to make a `ProtoOATraderReq` request and check the result. Let me know if there's a better way to do it.

Thanks for reading!

----

### Features
* cTrader | Add support for `stillConnected()` [#109](https://github.com/Reiryoku-Technologies/Mida/pull/109)
* Core | Define `stillConnected()` method to `MidaTradingAccount` for checking if the account is still connected to the trading platform [#109](https://github.com/Reiryoku-Technologies/Mida/pull/109)

2023-05-13 17:01 UTC, Vasile-Peste requested changes
I'm happy to see that you managed to understand the codebase and apply your idea on all integrations starting from the core.

I think that you did a great job with this solution, thank you!
I just asked two very small changes

2023-05-13 17:01 UTC, Vasile-Peste requested changes
I'm happy to see that you managed to understand the codebase and apply your idea on all integrations starting from the core 🥇 

I think that you did a great job with this solution, thank you!
I just asked two very small changes

2023-05-13 17:03 UTC, Vasile-Peste requested changes

2023-05-13 17:03 UTC, Vasile-Peste commented on src/playground/accounts/MidaPlaygroundAccount.ts
> +        throw unsupportedOperationError(this.platform);
Since Playground it's the simulation of a local exchange without any network connection, let's just return always true, what do you think?

2023-05-16 15:16 UTC, merged

2023-08-17 11:33 UTC, desoss commented
Hey @JoeGuest and @Vasile-Peste thanks for this great solution. 
Nevertheless, I have a problem with it, the `stillConnected` method is taking more than 30 seconds to give me back an answer.


I'm using the `stillConnected` method in a lambda and the problem raises after the first lambda invocation, the second invocation is triggered after a couple of minutes from the first one. 
Furthermore,  the same mida account is logged in other concurrent lambda invocations.